---

webhost_package: nginx

software_packages:
  - apt-transport-https
  - software-properties-common
  - git
  - curl
  - mailutils
  - sendmail-bin
  - sendmail

php_7_packages:
  - php7.0
  - php-gettext
  - php-memcached
  - php7.0-fpm
  - php7.0-zip
  - php7.0-cli
  - php7.0-curl
  - php7.0-gd
  - php7.0-intl
  - php7.0-mysql
  - php7.0-mbstring
  - php7.0-xml
  - php-xml-parser
  - php7.0-mcrypt

php_5_packages:
  - php5
  - php-pear
  - php5-xcache
  - php5-mcrypt
  - php5-xdebug
  - php-gettext
  - php5-curl
  - php5-gd
  - php5-mysql
  - php5-memcached
  - php5-intl
  - php-xml-parser
  - php5-fpm


stretch_repos:
  - 'deb http://ftp.us.debian.org/debian/ stretch-updates main'
  - 'deb-src http://ftp.us.debian.org/debian/ stretch-updates main'
  - 'deb http://ftp.us.debian.org/debian/ stretch-backports main'
  - 'deb-src http://ftp.us.debian.org/debian/ stretch-backports main'


mariadb_password: 'sqlpassword'

db_name: 'dbname'
db_admin_user: 'dbadmin'
db_admin_password: 'dbpassword'

#social_admin_user: 'socialadmin'
#social_admin_password: 'socialpassword'
social_domain: 'yourdomain.tld'

tls_my_email: 'email@yourdomain.tld'

hubzilla_dir: '/var/www/hubzilla'

#SSL cert, might need to redo later
letsencrypt_cmd: "letsencrypt"
letsencrypt_renew_hr: "7"
letsencrypt_renew_min: "0"
letsencrypt_renew_parms: "--noninteractive --quiet --no-self-upgrade --post-hook 'systemctl reload {{ webhost_package }}.service'"
