---
# Install Packages
- block:
  - name: Copy sources to make a file for stretch
    copy:
      src: /etc/apt/sources.list
      dest: /etc/apt/sources.list.d/stretch.list
      remote_src: yes

  - name: Remove NTC's repo from the copy
    lineinfile:
      path: /etc/apt/sources.list.d/stretch.list
      state: absent
      regexp: 'deb http://opensource.nextthing.co/chip/debian/repo jessie main'

  - name: Replace all instances of 'jessie' with 'stretch' in the new copy
    replace:
      path: /etc/apt/sources.list.d/stretch.list
      regexp: 'jessie'
      replace: 'stretch'
      backup: no

  - name: Add extra stretch repos
    apt_repository:
      repo: "{{ item }}"
      state: present
      filename: 'stretch'
      update_cache: no
    with_items: "{{ stretch_repos }}"

  - name: Update package list to stretch
    package:
      update_cache: yes
    ignore_errors: yes

  when: php_ver == 7
  tags:
    - php7

- name: Install Software packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: no
  with_items:  "{{ software_packages }}"

- name: Install PHP5 packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: no
  with_items:  "{{ php_5_packages }}"
  when: php_ver == 5
  tags:
    - php5

- name: Install PHP7 packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: no
  with_items:  "{{ php_7_packages }}"
  when: php_ver == 7
  tags:
    - php7

- name: Copy postactive archive to remote node
  copy:
    src: "{{ postactiv_archive }}"
    dest: "/tmp/"

- name: Unarchive postactiv
  unarchive:
    src: "/tmp/{{ postactiv_archive }}"
    dest: "/tmp/"
    remote_src: yes

- name: Copy extracted archive to /var/www/postactiv
  command: "mv /tmp/{{ postactiv_extracted }}/ /var/www/postactiv/"

- name: Clean temp files caused by this script
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/{{ postactiv_archive }}"
    - "/tmp/{{ postactiv_extracted }}"

- name: Set ownage to www-data and mode
  file:
    path: "{{ item }}"
    state: directory
    group: www-data
    mode: "g+w"
  with_items:
    - /var/www/postactiv
    - /var/www/postactiv/file
    - /var/www/postactiv/avatar
    - /var/www/postactiv/background

- name: Remove Apache2
  package:
    name: apache2
    state: absent
    purge: yes
    update_cache: no
  when: webhost_package != "apache2"

- name: Install {{ webhost_package }}
  package:
    name: "{{ webhost_package }}"
    state: installed
    update_cache: no

- name: Copy postActive install script
  copy:
    src: "install_postactiv.sh"
    dest: "/tmp/"
    mode: 0755
  tags:
    - test

- name: Run postActiv install script
  command: "/tmp/install_postactiv.sh {{ mariadb_password }} {{ db_admin_user }} {{ db_admin_password }} {{ social_admin_user }} {{ social_admin_password }} {{ social_domain }}"
  become: yes
  tags:
    - test
